facts:
  sample_size: 752
  healthy_preds: 688
  wrong_preds: 26
metrics:
  precision: 93.86
  recall: 97.31
  f1_score: 95.56
  accuracy: 91.49
matrix:
  true_pos: 688
  true_neg: 0
  false_pos: 19
  false_neg: 45
